import warnings

# Suppresses warnings generated by the code to keep the output clean.
warnings.filterwarnings('ignore')


from langchain_ibm import WatsonxLLM

# Facilitates interaction with IBM's Watsonx large language models.
granite_llm = WatsonxLLM(
    model_id="ibm/granite-3-2-8b-instruct",
    url="https://us-south.ml.cloud.ibm.com",
    project_id="skills-network",
    params={
        "max_new_tokens": 256,
        "temperature": 0.5,
        "top_p": 0.2,
    },
)


# Invokes IBM Watsonx LLM with a given prompt and parameters.
def llm_model(prompt_txt, params=None):
    model_id = "ibm/granite-3-2-8b-instruct"
    default_params = {
        "max_new_tokens": 256,
        "temperature": 0.5,
        "top_p": 0.2,
    }
    if params:
        default_params.update(params)

    granite_llm = WatsonxLLM(
        model_id=model_id,
        url="https://us-south.ml.cloud.ibm.com",
        project_id="skills-network",
        params=default_params
    )

    response = granite_llm.invoke(prompt_txt)

    return response


from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams

# A class from the ibm_watsonx_ai.metanames module that provides parameters for controlling text generation,
#       including max_new_tokens, min_new_tokens, temperature, top_p, and top_k.

# Get example values
GenParams().get_example_values()

# Use in parameters
parameters = {
    GenParams.MAX_NEW_TOKENS: 256,
    GenParams.TEMPERATURE: 0.5,
}